# Generated by Django 4.2.4 on 2023-10-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacto", "0002_rename_address_contacto_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacto",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
