# Generated by Django 4.1.12 on 2023-10-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0002_proyecto_date_proyecto_imageproj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="imageproj",
            field=models.FileField(null=True, upload_to="proyectos/"),
        ),
    ]
